service: website-lambda

custom:
  bucketName: ${cf:imageinput-dev.S3BucketImageinputdev}

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:Put*
      Resource:
        arn:aws:s3:::${self:custom.bucketName}/*

package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip

functions:
  post:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Post
    environment:
      bucketName: ${self:custom.bucketName}
    events:
      - http:
          method: post
          path: /upload
          cors: true