service: website

plugins:
  - serverless-s3-sync
  - serverless-pseudo-parameters
provider:
  name: aws
  region: eu-west-1
  stage: dev

custom:
  siteName: bucket-${self:service}-#{AWS::AccountId}-${self:provider.stage}
  s3Sync:
    - bucketName: ${self:custom.siteName}
      localDir: static

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: index.html

    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]